from typing import Any

class MutagenError(Exception): ...

class FileType:
    info: Any
    def get(self, key: str, default: Any = ...) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, key: object) -> bool: ...
