from collections.abc import Iterator
from typing import Any

class ID3NoHeaderError(Exception): ...

class Frame:
    def __init__(self, **kwargs: Any) -> None: ...

class TextFrame(Frame):
    text: list[str]

class APIC(Frame):
    mime: str
    data: bytes
    type: int
    encoding: int
    desc: str

class TIT2(TextFrame): ...
class TPE1(TextFrame): ...
class TPE2(TextFrame): ...
class TALB(TextFrame): ...
class TRCK(TextFrame): ...
class TPOS(TextFrame): ...
class TDRC(TextFrame): ...
class TCON(TextFrame): ...

class ID3:
    def __init__(self, filething: str = ..., **kwargs: Any) -> None: ...
    def add(self, frame: Frame) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
